spring.application.name=telegram

# Telegram Configuration
telegram.bot.username=${TELEGRAM_BOT_USERNAME}
telegram.bot.token=${TELEGRAM_BOT_TOKEN}
telegram.bot.allowed-users=${TELEGRAM_BOT_ALLOWED_USERS:}

# JPA Common Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Spring AI Vertex AI Gemini Configuration
spring.ai.vertex.ai.gemini.project-id=${VERTEX_AI_PROJECT_ID}
spring.ai.vertex.ai.gemini.location=${VERTEX_AI_LOCATION}
spring.ai.vertex.ai.gemini.chat.options.model=gemini-2.5-flash
spring.ai.vertex.ai.gemini.chat.options.temperature=0.2

# Spring AI Retry Configuration
spring.ai.retry.max-attempts=1
spring.ai.retry.on-client-errors=false
